Import swedish language pack #2664
AnySoftKeyboard/AnySoftKeyboard pull request #3400
Opened 2022-06-13 08:21 UTC by jswetzen

Building and installing on my phone works, it's just the version that the app store thinks is lower than the old Swedish language pack.

It's mostly an import straight from the old repo, but I updated the Svorak layout to match Dvorak and changed the flag svg as it wouldn't generate icons properly.

2022-06-13 17:26 UTC, menny requested changes
Great stuff!

Can you also comment here (on the PR) from where did you get the dictionary?

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/apk/build.gradle
> +ext.shouldBePublished = false
should be `true`, we have the signing keys for this pack

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/apk/build.gradle
> +ext.notPublishingReason = "Initial version has not been published yet"
Can be removed, if we are publishing

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/apk/src/main/play/contact-email.txt
> +playstore@evendanan.net
```suggestion
playstore.US@evendanan.net
```

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/apk/src/main/play/release-notes/en-US/alpha.txt
> +* Initial release
```suggestion
* Svorak update.
```

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/pack/src/main/res/xml/swedish_dictionaries.xml
> +</Dictionaries>
We require that all text files end with a `newline`.

2022-06-13 17:26 UTC, menny commented on addons/languages/swedish/pack/src/main/res/xml/swedish_keyboards.xml
> +</Keyboards>
Same here, `newline` missing.

2022-06-13 17:47 UTC, jswetzen commented
Thanks! The dictionary is the same as the existing Swedish pack. I downloaded from AOSP first, but it seemed identical.
-------- Originalmeddelande --------
På 13 juni 2022 19:26, Menny Even Danan skrev:

> @menny requested changes on this pull request.
>
> Great stuff!
>
> Can you also comment here (on the PR) from where did you get the dictionary?
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/apk/build.gradle](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895960828):
>
>> @@ -0,0 +1,8 @@
> +ext.shouldBePublished = false
>
> should be true, we have the signing keys for this pack
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/apk/build.gradle](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895960963):
>
>> @@ -0,0 +1,8 @@
> +ext.shouldBePublished = false
> +ext.notPublishingReason = "Initial version has not been published yet"
>
> Can be removed, if we are publishing
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/apk/src/main/play/contact-email.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895962458):
>
>> @@ -0,0 +1 @@
> ***@***.***
>
> ⬇️ Suggested change
>
> ***@***.***
> ***@***.***
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/apk/src/main/play/release-notes/en-US/alpha.txt](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895963348):
>
>> @@ -0,0 +1 @@
> +* Initial release
>
> ⬇️ Suggested change
>
> -* Initial release
> +* Svorak update.
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/pack/src/main/res/values/strings.xml](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895964043):
>
>> +    <string name="store_title">Swedish Language Pack</string>
> +    <string name="store_promo">Swedish language pack for AnySoftKeyboard</string>
> +    <string name="store_description">AnySoftKeyboard keyboards pack:
> +      Swedish keyboard and dictionary.
> +
> +      This is an expansion pack for AnySoftKeyboard.
> +      Install AnySoftKeyboard first, and then select the desired layout from AnySoftKeyboard\'s Settings->Keyboards menu.</string>
>
> Why do we need these?
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/pack/src/main/res/xml/swedish_dictionaries.xml](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895964527):
>
>> @@ -0,0 +1,13 @@
> +<?xml version="1.0" encoding="UTF-8"?>
> +<Dictionaries>
> +<!-- Dictionary attributes:
> + "nameResId" : the name of the dictionary. Should be short. Reference to a string in values.xml
> + "locale" : the ID of the dictionary's (ISO) locale, e.g., "en", "iw", "ar", "ru", etc. The keyboard should declare the same locale.
> + "id" : UUID for this dictionary. Obtain from here: http://www.famkruithof.net/uuid/uuidgen
> + "dictionaryResourceId" : a reference to the raw resource of the words dictionary
> + "autoTextResourceId" : a reference to a common typing mistakes XML.
> + -->
> +<Dictionary ***@***.***/dictionary_name" locale="sv" id="935fe956-c7f9-4dc6-b2d0-5a389005c826" type="binary_resource"
> +		***@***.***/swedish_words_dict_array" ***@***.***/autotext"
> +		description="A swedish dictionary generated from the AOSP sources"/>
> +</Dictionaries>
>
> We require that all text files end with a newline.
>
> ---------------------------------------------------------------
>
> In [addons/languages/swedish/pack/src/main/res/xml/swedish_keyboards.xml](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#discussion_r895964700):
>
>> @@ -0,0 +1,5 @@
> +<?xml version="1.0" encoding="UTF-8"?>
> +<Keyboards>
> +	<Keyboard ***@***.***/swedish_keyboard" ***@***.***/swedish_qwerty" id="8dd7b7fa-91c7-4be1-9b9c-cdfee1b34a47" index="1" defaultDictionaryLocale="sv" description="Created with jtlallo"/>
> +	<Keyboard ***@***.***/svorak_keyboard" ***@***.***/svorak" id="595f7064-e9d8-40cc-9348-78ea065aff53" index="2" defaultDictionaryLocale="sv" description="Created by Henrik Andersson"/>
> +</Keyboards>
>
> Same here, newline missing.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#pullrequestreview-1004684586), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAYTHPXNYJAVWFDS673HLY3VO5VMRANCNFSM5YTLSUXA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-06-13 18:37 UTC, jswetzen commented
Actually when I think about it, I got curious about generating a new dictionary by combining AOSP with something like the OpenSubtitles corpus. 😏
But that's for another PR!
-------- Originalmeddelande --------
På 13 juni 2022 20:18, Menny Even Danan skrev:

> Got it. Once the requested changes are handled, I'll merge. Thank you
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3400#issuecomment-1154234081), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAYTHPUNFDK6FDBO3K3NC2TVO53OZANCNFSM5YTLSUXA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-06-13 18:40 UTC, menny commented
yes! go for it!
You can generate the OpenSubtitles word-list in a separate file, and our build-system will merge it with AOSP.

2022-06-13 18:40 UTC, menny commented
But, maybe it is for another PR.

2022-06-16 06:08 UTC, jswetzen commented on addons/languages/swedish/pack/src/main/res/values/strings.xml
> +      Install AnySoftKeyboard first, and then select the desired layout from AnySoftKeyboard\'s Settings->Keyboards menu.</string>
We don't! I just imported them from the existing pack and didn't think about it.

2022-06-17 19:27 UTC, menny commented
A lot of small fixes to do here. So, I'm opening another PR: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3411.

I'll push the fixes on top of your commit. Thanks.

2022-06-17 19:27 UTC, closed without merging