Hacker keyboard layouts
AnySoftKeyboard/AnySoftKeyboard pull request #3740
Opened 2023-06-12 10:18 UTC by asl97

Hacker Keyboard gotten quite broken in recent android version, this bring the three basic hacker keyboard layout to AnySoftKeyboard

https://github.com/klausw/hackerskeyboard/issues/875

![Screenshot_default](https://github.com/AnySoftKeyboard/AnySoftKeyboard/assets/4752645/35231e57-beb4-4936-8b1a-de0dc70106bb)
![Screenshot_compact](https://github.com/AnySoftKeyboard/AnySoftKeyboard/assets/4752645/f2fdf3b4-f804-4360-8170-948f98802910)
![Screenshot_full](https://github.com/AnySoftKeyboard/AnySoftKeyboard/assets/4752645/2ea63997-887e-484d-81e2-0b45da2bb6f7)

blank out key are those not supported on AnySoftKeyboard and currently have blank placeholder

2023-07-10 18:21 UTC, menny commented on addons/languages/hackerkeyboard/apk/flag/flag.svg
Maybe an SVG of an `h`? or something that will signify Hacker's keyboard?
Also, I think that I'm not allowed to use the name Hacker Keyboard since it is a copyright. I'm not sure, though

2023-07-10 18:22 UTC, menny commented
what are the missing keys?

2023-07-10 19:02 UTC, asl97 commented
> what are the missing keys?

Alt - which seem to cause hangs and doesn't seem to register

Super/Win/Meta - I don't see it in the api? eg: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/main/api/src/main/res/values/functional_key_codes.xml

Dpad Center - This is a weird button, I am not sure what or where it's suppose to be used, but I assume it's the center middle button of a remote control

____

If we want to talk about the other layout not included like the function layout, then there are tons of keys like the fn keys

2023-07-10 19:35 UTC, asl97 commented on addons/languages/hackerkeyboard/apk/flag/flag.svg
Something that would signify HK would be `Esc` but since you bring up copyright, I ain't sure...

https://github.com/klausw/hackerskeyboard/blob/master/app/src/main/res/drawable-hdpi/icon.png
____

If you mean calling the pack `Hacker Keyboard` is an issue, I assume that can easily be changed.

There should be no issue for a description like `Hacker Keyboard Layout Pack for AnySoftKeyboard` as per `except as required for reasonable and customary use in describing the origin of the Work`

@klausw would be great if you could pitch in on if it be a issue for the name and logo to be used

2023-07-10 20:32 UTC, klausw commented on addons/languages/hackerkeyboard/apk/flag/flag.svg
I'm fine with using a name such as `Hacker's Keyboard Layout Pack for AnySoftKeyboard`, or anything similar that makes it clear that it's a derived work and not an official "Hacker's Keyboard" release. You're welcome to use the Esc logo if you want, though I think it would be best to modify it (for example by combining it with an AnySoftKeyboard logo) to avoid confusion.

2023-07-12 19:15 UTC, menny requested changes
this looks good. Can you share screenshots of the layouts on your device?

2023-07-12 19:15 UTC, menny commented on addons/languages/hackerkeyboardlayout/apk/src/main/play/contact-email.txt
`playstore.US@evendanan.net`

2023-07-12 19:15 UTC, menny commented on addons/languages/hackerkeyboardlayout/apk/src/main/play/contact-website.txt
`https://anysoftkeyboard.github.io/`

2023-07-15 19:36 UTC, asl97 commented
> this looks good. Can you share screenshots of the layouts on your device? Place the screenshots under `apk/src/main/play/listings/en-US/graphics/phone-screenshots`

MIUI takes screenshot in jpg, hope it's not an issue, there are a few other jpg screenshots

2023-07-15 19:37 UTC, asl97 commented on addons/languages/hackerkeyboardlayout/apk/build.gradle
> +ext.shouldBePublished = false
Does this need to be changed to True and below removed?

2023-07-15 19:42 UTC, asl97 commented on addons/languages/hackerkeyboardlayout/apk/src/main/play/listings/en-US/graphics/phone-screenshots/Screenshot_Landscape.jpg
I feel it best to showcase the full layout for the landscape screenshot

2023-07-15 19:42 UTC, asl97 commented on addons/languages/hackerkeyboardlayout/apk/src/main/play/listings/en-US/graphics/phone-screenshots/Screenshot_Portrait.jpg
I feel the compact layout is more unique and a better fit than the standard hacker keyboard layout

It's the reason and my motivation to even port the layouts over to AnySoftKeyboard

2023-07-17 15:41 UTC, menny approved these changes

2023-07-19 15:57 UTC, menny commented
@asl97 there is a lint error: `/__w/AnySoftKeyboard/AnySoftKeyboard/addons/languages/hackerkeyboardlayout/pack/src/main/res/values/hacker_strings.xml:3: Error: The resource R.string.hacker_keyboard_name appears to be unused [UnusedResources]`

2023-08-23 02:22 UTC, Pablo1107 commented
@asl97 if you need help fixing the linting error I can try to provide a PR to your branch in order to get this merged.

2023-08-23 22:08 UTC, asl97 commented
After a crash, Windows lags to the point of being unusable when booting with my HDD, which contain all the android related stuff

I am guessing the data is more or less dead since linux fsck ntfs refuses to fix it due to unsupported case and boot chkdsk just freezes too. so I reformatted the whole thing.

Also, I already had "Allow edits by maintainers" checked and this is just lint, I figure someone can just remove that line or something.

And other stuff happened (r/place) and this sort of slip my mind.

2023-09-28 18:26 UTC, menny approved these changes

2023-09-28 18:38 UTC, merged

2023-09-28 18:38 UTC, menny commented
Thank you all!

2023-09-28 19:00 UTC, Pablo1107 commented
Thanks for reviewing and merging. Sorry to hijack but is there a GitHub Actions that build from main for testing or should I wait for beta?

2023-09-28 19:18 UTC, asl97 commented
> Thanks for reviewing and merging. Sorry to hijack but is there a GitHub Actions that build from main for testing or should I wait for beta?

https://github.com/AnySoftKeyboard/AnySoftKeyboard/actions/runs/6343126822

the apks archive contain the apk for this set of layout

2024-03-13 03:06 UTC, menny commented
The release is available on the Play Store: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hackerkeyboardlayout&pli=1