added Polytonic Greek Keyboard
AnySoftKeyboard/AnySoftKeyboard pull request #4041
Opened 2024-08-28 14:04 UTC by semaurer01

I wanted a better way to type in Polytonic Greek. [Apptide](https://ancient-languages-pack-for-anysoftkeyboard.en.aptoide.com/app) has an ancient languages pack that supports Polytonic Greek, but it is hard to use because of the large popup menus. So I have created one that uses combining diacritics. and lists them in a row for easy access. now there is some difficulty because a lot of systems including mine(android 15) do fine if one types: Vowel, Breathing Mark, Tonos(ἔ); but have trouble if one types: Vowel, Tonos Breathing Mark, (έ̓). but I know not how to solve this problem in AnySoftKeyboard. I don't think I did anything "Copyright-able" so do with this keyboard as you please. I do not know whether it really belongs in the Greek package or in a new package for itself.

2024-09-28 00:51 UTC, menny commented on addons/languages/greek/pack/src/main/res/xml/greek_qwerty.xml
I think you do not have changes in this file, right?
Please revert the changes, as this will not pass CI checks.

2024-09-28 00:52 UTC, menny requested changes
thanks for the new layout. I have one request for a change

2024-09-28 15:11 UTC, semaurer01 commented on addons/languages/greek/pack/src/main/res/xml/greek_qwerty.xml
I do not understand the objection. Being new to git I know not: what are CI checks? nor do I know how to revert changes to a specific file. please explain the issue in more detail.

2024-09-29 12:21 UTC, menny commented on addons/languages/greek/pack/src/main/res/xml/greek_qwerty.xml
You have introduced changes in this file. These changes are not required and, in fact, include code-style changes that are not compatible with the project.

2024-09-29 19:08 UTC, semaurer01 commented on addons/languages/greek/pack/src/main/res/xml/greek_qwerty.xml
I think I have resolved this issue.

2024-10-17 07:00 UTC, menny approved these changes

2024-10-17 07:00 UTC, merged